import { buildApiUrl } from "../services/api";

function ChartGallery({ charts = [], emptyMessage = "No Python charts generated yet." }) {
  if (!charts.length) {
    return <p className="muted">{emptyMessage}</p>;
  }

  return (
    <div className="chart-grid">
      {charts.map((chart) => (
        <article key={chart.id || chart.file} className="chart-card">
          <img
            src={buildApiUrl(chart.url || "")}
            alt={chart.title || chart.file || "Generated chart"}
            loading="lazy"
          />
          <div className="chart-meta">
            <h4>{chart.title || chart.file}</h4>
            <p>{chart.description || "Generated by Python analytics pipeline."}</p>
          </div>
        </article>
      ))}
    </div>
  );
}

export default ChartGallery;
